#ifndef _OPCODES_H
#define _OPCODES_H

{# If you see this message, you're looking at the template. Ignore the next line. -#}
/* This file is generated by a template. Do not edit it directly. */

#include "machine.h"

/*
 * Function representing the implementation of an opcode.
 * The return value indicates whether the machine should stop running
 * after this instruction:
 *
 * 0: Keep going
 * 1: Stop
 */
typedef int (*opcode_f)(machine_state_t *);

{% for code, name in opcodes -%}
int opcode_{{ name }}(machine_state_t *);
{% endfor %}

#endif // _OPCODES_H
